import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    kotlin("plugin.serialization") version "2.3.20"
    alias(libs.plugins.sqldelight)

}

val generatedSecretsDir = layout.buildDirectory.dir("generated/secrets/commonMain/kotlin")

val generateBuildSecrets by tasks.registering {
    group = "build setup"
    description = "Generates BuildSecrets.kt with API keys from local.properties / env."

    val localProps = rootProject.file("local.properties")
    val envKey = providers.environmentVariable("NEWS_API_KEY")
    val outDirProvider = generatedSecretsDir

    if (localProps.exists()) inputs.file(localProps)
    inputs.property("envSet", envKey.isPresent)
    outputs.dir(outDirProvider)

    doLast {
        val resolvedKey: String = envKey.orNull?.takeIf { it.isNotBlank() } ?: run {
            if (!localProps.exists()) "" else {
                val props = Properties().apply {
                    localProps.inputStream().use { load(it) }
                }
                props.getProperty("NEWS_API_KEY", "").orEmpty()
            }
        }
        val escaped = resolvedKey.replace("\\", "\\\\").replace("\"", "\\\"")

        val outFile = outDirProvider.get()
            .file("com/multiplatform/kanoonify/BuildSecrets.kt").asFile
        outFile.parentFile.mkdirs()
        outFile.writeText(
            """
            |// AUTO-GENERATED by `generateBuildSecrets` Gradle task. DO NOT EDIT.
            |// Source: NEWS_API_KEY env var > local.properties#NEWS_API_KEY.
            |package com.multiplatform.kanoonify
            |
            |internal object BuildSecrets {
            |    /** NewsAPI.org developer key. Empty when no key is configured. */
            |    const val NEWS_API_KEY: String = "$escaped"
            |}
            |""".trimMargin()
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true

            linkerOpts.add("-lsqlite3")
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.ktor.client.android)
            implementation(libs.sqldelight.android)
            implementation(libs.androidx.biometric)
            implementation(libs.androidx.fragment.ktx)
        }
        commonMain {

            kotlin.srcDir(generateBuildSecrets)
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.icons.tabler)
                implementation(libs.compose.icons.feather)
                implementation(libs.compose.ui)
                implementation(libs.compose.components.resources)
                implementation(libs.androidx.lifecycle.viewmodelCompose)
                implementation(libs.androidx.lifecycle.runtimeCompose)
                implementation(libs.navigation.compose)
                implementation(libs.ktor.client.cio)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.sqldelight.runtime)
                implementation(libs.sqldelight.coroutines)
            }
        }
        iosMain.dependencies {
            implementation(libs.sqldelight.native)
            implementation(libs.ktor.client.darwin)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

android {
    namespace = "com.multiplatform.kanoonify"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.multiplatform.kanoonify"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

sqldelight {
    databases {
        create("KanoonifyDatabase") {
            packageName.set("com.multiplatform.kanoonify.db")
        }
    }
}

dependencies {
    debugImplementation(libs.compose.uiTooling)
    testImplementation(libs.junit)
}
